### ISSUE TITLE
A Toggle to turn on/off blur effect

### ISSUE THREAD

**Issue by ninadnaik10** [tusharnankani/blurrit#3]
When the extension is installed, the blurring effect gets activated and we cannot see the chat names when needed. A toggle which can turn on/off blur effect can be useful.

**Comment by tusharnankani** [comment]
Yes
Very crucial.

**Comment by anxkhn** [comment]
Agreed! This was needed.

**Comment by tusharnankani** [comment]
UX Fix for toggle: https://github.com/tusharnankani/blurrit/commit/394c1c79f14216aef544da66121a831d81859e87#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R57-R62

Without the need of `index.html` and a `background.js`: retaining the size of the extension.

**Comment by tusharnankani** [comment]
Closed via https://github.com/tusharnankani/blurrit/commit/078cfe6711368b5c865307304c453c46245aa74f

Added a simple onclick toggle: [v0.3-alpha](https://github.com/tusharnankani/blurrit/releases/tag/v0.3)
